### ISSUE TITLE
Area equilibrium method

### ISSUE THREAD

**Issue by marcosertoli** [ukaea/Indica#37]
**Feature request**
Poloidal cross-sectional area is calculated within the enclosed_volume method of equilibrium.py (variable name = "area").

**Describe the solution you'd like**
Make the calculation of "area" a separate method of equilibrium.py and call it inside enclosed volume.

**Additional context**
The "area" is necessary for computation of several plasma quantities so the use of a separate method is necessary.

**Comment by elitherl** [comment]
Reopened by reverting #43
