### ISSUE TITLE
black hook requires newer version of pre-commit

### ISSUE THREAD

**Issue by elitherl** [ukaea/Indica#41]
**Describe the bug**
Running pre-commit fails as `black` hook requires a newer version of `pre-commit` than the one defined in `.pre-commit-config.yaml`

```bash
[ERROR] The hook `black` requires pre-commit version 2.9.2 but version 2.6.0 is installed.  Perhaps run `pip install --upgrade pre-commit`.
```

Would the best solution be to select a specific version of `black` (e.g. `19.10b0` as in `poetry.lock`?) instead of currently used stable, or update the version of `pre-commit` installed by poetry?

**Comment by cmacmackin** [comment]
Either would work. If you update the version of `pre-commit` then make sure to do this via `poetry` so your lock-file gets updated accordingly.

**Comment by elitherl** [comment]
Seems to have been an issue with my specific setup and not the respository settings, `poetry update` fixed it without needing to change anything
