### ISSUE TITLE
Change LOS coordinates from (R,z,T) to (x,y,z)

### ISSUE THREAD

**Issue by marcosertoli** [ukaea/Indica#64]
**Describe the bug**
Current start and end LOS coordinates given in input the the abstract reader are in cartesian space, but the variable names are called (R,z,T) and thus misleading. The variable names should be changed to (x,y,z) where x=R, y=T, z=z to reflect the real meaning of the spatial coordinates.

**Expected behavior**
The functions/methods should work exactly as they do now, changing only the variable names and order in the calls to reflect the (x,y,z) convention.

**Additional context**
In the IDL code at the origin of Indica, only diagnostics viewing on a poloidal plane (R,z) were used. The need to expand the this further lead to the addition of the T coordinate, but the variable names were never changed.

**Comment by gadgil48** [comment]
How widespread should this change be? Is it just the labelling in `indica/reader/abstractreader.py` and its dependencies _or_ is it a code-wide labelling change (including `LinesOfSightTransform` and its dependencies)?
